// Application IDs remain stable so saved projects and model mentions keep working.
export const FAL_ENDPOINTS: Record<string, string> = {
  'seedream/5-pro-text-to-image': 'bytedance/seedream/v5/pro/text-to-image',
  'seedream/5-pro-image-to-image': 'bytedance/seedream/v5/pro/edit',
  'gpt-image-2-text-to-image': 'openai/gpt-image-2',
  'gpt-image-2-image-to-image': 'openai/gpt-image-2/edit',
  'nano-banana-2-text-to-image': 'fal-ai/nano-banana-2',
  'nano-banana-2-image-to-image': 'fal-ai/nano-banana-2/edit',
  'nano-banana-2-lite-text-to-image': 'google/nano-banana-2-lite',
  'nano-banana-2-lite-image-to-image': 'fal-ai/nano-banana-2/edit',
  'nano-banana-pro-text-to-image': 'fal-ai/nano-banana-pro',
  'nano-banana-pro-image-to-image': 'fal-ai/nano-banana-pro/edit',
  'bytedance/seedance-2-text-to-video': 'bytedance/seedance-2.0/text-to-video',
  'bytedance/seedance-2-image-to-video': 'bytedance/seedance-2.0/image-to-video',
  'bytedance/seedance-2-reference-to-video': 'bytedance/seedance-2.0/reference-to-video',
  'bytedance/seedance-2-5-text-to-video': 'bytedance/seedance-2.5/text-to-video',
  'bytedance/seedance-2-5-image-to-video': 'bytedance/seedance-2.5/image-to-video',
  'bytedance/seedance-2-5-reference-to-video': 'bytedance/seedance-2.5/reference-to-video',
  'minimax-h3/text-to-video': 'minimax/h3/text-to-video',
  'minimax-h3/image-to-video': 'minimax/h3/image-to-video',
  'minimax-h3/reference-to-video': 'minimax/h3/reference-to-video',
  'wan/3-0-video-text-to-video': 'alibaba/wan-3.0/text-to-video',
  'wan/3-0-video-image-to-video': 'alibaba/wan-3.0/image-to-video',
  'wan/3-0-video-reference-to-video': 'alibaba/wan-3.0/reference-to-video',
}
